# install won't overwrite, update will

install:
	cp dot_bash_functions ~/.bash_functions
	cp dot_bashrc ~/.bashrc
	cp dot_profile ~/.profile

update:
	cp -f dot_bash_functions ~/.bash_functions
	cp -f dot_bashrc ~/.bashrc
	cp -f dot_profile ~/.profile
